### ISSUE TITLE
Cannot instantiate abstract class Zend\Diactoros\ServerRequestFactory

### ISSUE THREAD

**Issue by 2Cubes** [getsentry/sentry-php#1513]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.17.0

### Steps to Reproduce

ZF 2.5.3

I'm trying to throw an error 
`\Sentry\captureLastError();`

Also tried to send messages
`\Sentry\captureMessage('Something went wrong');`

### Expected Result

There is always an attempt to instantiate an abstract class

### Actual Result

```php
Cannot instantiate abstract class Zend\Diactoros\ServerRequestFactory, <path to project>/vendor/php-http/discovery/src/ClassDiscovery.php, 219
#0 <path to project>/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php(74): Http\Discovery\ClassDiscovery::instantiateClass('Zend\\Diactoros\\...')
#1 <path to project>/vendor/php-http/discovery/src/Psr17Factory.php(96): Http\Discovery\Psr17FactoryDiscovery::findServerRequestFactory()
#2 <path to project>/vendor/php-http/discovery/src/Psr17Factory.php(104): Http\Discovery\Psr17Factory->createServerRequest('GET', Object(GuzzleHttp\Psr7\Uri), Array)
#3 <path to project>/vendor/sentry/sentry/src/Integration/RequestFetcher.php(25): Http\Discovery\Psr17Factory->createServerRequestFromGlobals()
#4 <path to project>/vendor/sentry/sentry/src/Integration/RequestIntegration.php(125): Sentry\Integration\RequestFetcher->fetchRequest()
#5 <path to project>/vendor/sentry/sentry/src/Integration/RequestIntegration.php(117): Sentry\Integration\RequestIntegration->processEvent(Object(Sentry\Event), Object(Sentry\Options))
#6 <path to project>/vendor/sentry/sentry/src/State/Scope.php(378): Sentry\Integration\RequestIntegration->Sentry\Integration\{closure}(Object(Sentry\Event), Object(Sentry\EventHint))
#7 <path to project>/vendor/sentry/sentry/src/Client.php(292): Sentry\State\Scope->applyToEvent(Object(Sentry\Event), Object(Sentry\EventHint))
#8 <path to project>/vendor/sentry/sentry/src/Client.php(169): Sentry\Client->prepareEvent(Object(Sentry\Event), Object(Sentry\EventHint), Object(Sentry\State\Scope))
#9 <path to project>/vendor/sentry/sentry/src/Client.php(161): Sentry\Client->captureEvent(Object(Sentry\Event), Object(Sentry\EventHint), Object(Sentry\State\Scope))
#10 <path to project>/vendor/sentry/sentry/src/Client.php(202): Sentry\Client->captureException(Object(ErrorException), Object(Sentry\State\Scope), Object(Sentry\EventHint))
#11 <path to project>/vendor/sentry/sentry/src/State/Hub.php(166): Sentry\Client->captureLastError(Object(Sentry\State\Scope), NULL)
#12 <path to project>/vendor/sentry/sentry/src/functions.php(65): Sentry\State\Hub->captureLastError(NULL)
#13 <path to project>/module/Application/src/Application/Controller/IndexController.php(76): Sentry\captureLastError()
#14 <path to project>/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Application\Controller\IndexController->indexAction()
#15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 <path to project>/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 <path to project>/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 <path to project>/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#19 <path to project>/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 <path to project>/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#22 <path to project>/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 <path to project>/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#24 <path to project>/public/index.php(79): Zend\Mvc\Application->run()
```

**Comment by 2Cubes** [comment]
I added allow-plugins, But the error remains
Installed with `composer require sentry/sdk `command
composer version 2.5.5

**Comment by 2Cubes** [comment]
What ideas? What else can you try?

**Comment by cleptric** [comment]
There is no version `2.5.5` of the Zend framework. Looking at your stack trace, are you referring to https://github.com/zendframework/zend-mvc instead?

A few options you can take:

1. Disable the `RequestIntegration` https://docs.sentry.io/platforms/php/integrations/#custom-integrations
2. Use a version of the SDK before `3.17.0`.

The last version of `Zend\Diactoros\ServerRequestFactory` is not an abstract class anymore, this change happened five years ago.
