### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to a member function getClientFilename() on array

### ISSUE THREAD

**Issue by 4n70w4** [getsentry/sentry-php#825]
In case if `$uploadedFiles` is array of arrays of files.

![image](https://user-images.githubusercontent.com/38257723/58558536-cb719780-8229-11e9-95e0-e30aaf067db5.png)

![image](https://user-images.githubusercontent.com/38257723/58558632-04aa0780-822a-11e9-8caf-fd3142c623fb.png)

`PHP Fatal error: Uncaught Error: Call to a member function getClientFilename() on array in /var/www/app/vendor/sentry/sentry/src/Integration/RequestIntegration.php on line 178`

```
#0 /var/www/app/vendor/sentry/sentry/src/Integration/RequestIntegration.php(115): Sentry\Integration\RequestIntegration->captureRequestBody(Object(Zend\Diactoros\ServerRequest))
#1 /var/www/app/vendor/sentry/sentry/src/Integration/RequestIntegration.php(66): Sentry\Integration\RequestIntegration::applyToEvent(Object(Sentry\Integration\RequestIntegration), Object(Sentry\Event))
#2 /var/www/app/vendor/sentry/sentry/src/State/Scope.php(304): Sentry\Integration\RequestIntegration->Sentry\Integration\{closure}(Object(Sentry\Event), Array)
#3 /var/www/app/vendor/sentry/sentry/src/Client.php(159): Sentry\State\Scope->applyToEvent(Object(Sentry\Event), Array)
#4 /var/www/app/vendor/sentry/sentry/src/Client.php(104): Sentry\Client->prepareEvent(Array, Object(Sentry\State\Scope))
#5 /var/www/app/vendor/sentry/sentry/src/Client.php(96): Sentry\Client->captureEvent(Array, Object(Sentry\State\Scope))
#6 /var/www/app/vendor/sentry/sentry/src/State/Hub.php(140): Sentry\Client->captureException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), Object(Sentry\State\Scope))
```

**Comment by 4n70w4** [comment]
Quick workaround:

```patch
Index: vendor/sentry/sentry/src/Integration/RequestIntegration.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- vendor/sentry/sentry/src/Integration/RequestIntegration.php	(date 1559134603221)
+++ vendor/sentry/sentry/src/Integration/RequestIntegration.php	(date 1559134603221)
@@ -174,6 +174,10 @@
 
             /** @var UploadedFileInterface $uploadedFile */
             foreach ($uploadedFiles as $uploadedFile) {
+                if(is_array($uploadedFile) ) {
+                    continue;
+                }
+
                 $requestData[$fieldName][] = [
                     'client_filename' => $uploadedFile->getClientFilename(),
                     'client_media_type' => $uploadedFile->getClientMediaType(),

```

This does not solve the problem, but hides it.

**Comment by Jean85** [comment]
Which lib (and version) are you using for PSR-7? Diactoros?

**Comment by 4n70w4** [comment]
@Jean85 I don't known. The one that is used in Laravel 5.8. Initially, the request was for `sentry-laravel`.

**Comment by Jean85** [comment]
Please check on your project with `composer show -t sentry/sentry-laravel`.

**Comment by 4n70w4** [comment]
`composer show -t sentry/sentry-laravel`

```
sentry/sentry-laravel 1.0.1 Laravel SDK for Sentry (https://sentry.io)
├──illuminate/support 5.0.*|5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.*
├──php ^7.1
└──sentry/sdk ^2.0
   ├──http-interop/http-factory-guzzle ^1.0
   │  ├──guzzlehttp/psr7 ^1.4.2
   │  │  ├──php >=5.4.0
   │  │  ├──psr/http-message ~1.0
   │  │  │  └──php >=5.3.0
   │  │  └──ralouphie/getallheaders ^2.0.5
   │  │     └──php >=5.3
   │  └──psr/http-factory ^1.0
   │     ├──php >=7.0.0
   │     └──psr/http-message ^1.0
   │        └──php >=5.3.0
   ├──php-http/curl-client ^1.0|^2.0
   │  ├──ext-curl *
   │  ├──php ^5.5 || ^7.0
   │  ├──php-http/discovery ^1.0
   │  │  └──php ^5.5 || ^7.0
   │  ├──php-http/httplug ^1.0
   │  │  ├──php >=5.4
   │  │  ├──php-http/promise ^1.0
   │  │  └──psr/http-message ^1.0
   │  │     └──php >=5.3.0
   │  ├──php-http/message ^1.2
   │  │  ├──clue/stream-filter ^1.4
   │  │  │  └──php >=5.3
   │  │  ├──php ^5.4 || ^7.0
   │  │  ├──php-http/message-factory ^1.0.2
   │  │  │  ├──php >=5.4
   │  │  │  └──psr/http-message ^1.0
   │  │  │     └──php >=5.3.0
   │  │  └──psr/http-message ^1.0
   │  │     └──php >=5.3.0
   │  └──php-http/message-factory ^1.0.2
   │     ├──php >=5.4
   │     └──psr/http-message ^1.0
   │        └──php >=5.3.0
   └──sentry/sentry ^2.0.1
      ├──ext-json *
      ├──ext-mbstring *
      ├──jean85/pretty-package-versions ^1.2
      │  ├──ocramius/package-versions ^1.2.0
      │  │  ├──composer-plugin-api ^1.0.0
      │  │  └──php ^7.1.0
      │  └──php ^7.0
      ├──php ^7.1
      ├──php-http/async-client-implementation ^1.0
      ├──php-http/client-common ^1.5|^2.0
      │  ├──php ^5.4 || ^7.0
      │  ├──php-http/httplug ^1.1
      │  │  ├──php >=5.4
      │  │  ├──php-http/promise ^1.0
      │  │  └──psr/http-message ^1.0
      │  │     └──php >=5.3.0
      │  ├──php-http/message ^1.6
      │  │  ├──clue/stream-filter ^1.4
      │  │  │  └──php >=5.3
      │  │  ├──php ^5.4 || ^7.0
      │  │  ├──php-http/message-factory ^1.0.2
      │  │  │  ├──php >=5.4
      │  │  │  └──psr/http-message ^1.0
      │  │  │     └──php >=5.3.0
      │  │  └──psr/http-message ^1.0
      │  │     └──php >=5.3.0
      │  ├──php-http/message-factory ^1.0
      │  │  ├──php >=5.4
      │  │  └──psr/http-message ^1.0
      │  │     └──php >=5.3.0
      │  └──symfony/options-resolver ^2.6 || ^3.0 || ^4.0
      │     └──php ^7.1.3
      ├──php-http/discovery ^1.6.1
      │  └──php ^5.5 || ^7.0
      ├──php-http/httplug ^1.1|^2.0
      │  ├──php >=5.4
      │  ├──php-http/promise ^1.0
      │  └──psr/http-message ^1.0
      │     └──php >=5.3.0
      ├──php-http/message ^1.5
      │  ├──clue/stream-filter ^1.4
      │  │  └──php >=5.3
      │  ├──php ^5.4 || ^7.0
      │  ├──php-http/message-factory ^1.0.2
      │  │  ├──php >=5.4
      │  │  └──psr/http-message ^1.0
      │  │     └──php >=5.3.0
      │  └──psr/http-message ^1.0
      │     └──php >=5.3.0
      ├──psr/http-message-implementation ^1.0
      ├──ramsey/uuid ^3.3
      │  ├──paragonie/random_compat ^1.0|^2.0|9.99.99
      │  │  └──php ^7
      │  ├──php ^5.4 || ^7.0
      │  └──symfony/polyfill-ctype ^1.8
      │     └──php >=5.3.3
      ├──symfony/options-resolver ^2.7|^3.0|^4.0
      │  └──php ^7.1.3
      └──zendframework/zend-diactoros ^1.4|^2.0
         ├──php ^7.1
         ├──psr/http-factory ^1.0
         │  ├──php >=7.0.0
         │  └──psr/http-message ^1.0
         │     └──php >=5.3.0
         └──psr/http-message ^1.0
            └──php >=5.3.0
```

**Comment by Jean85** [comment]
This doesn't seems to be specific to a vendor, we're not following PSR-7 spec to the dot. We need to address this better: https://www.php-fig.org/psr/psr-7/#16-uploaded-files

I've opened #827 to fix this.
