### ISSUE TITLE
Fatal exception thrown upon submitting a custom exception

### ISSUE THREAD

**Issue by miraclebg** [getsentry/sentry-php#879]
- Sentry v2.1.3 installed through composer.
- PHP 7.3.9

Custom logging an exception like this:

```
 /** @var Throwable $exception */
        $exception = $event['exception'];

        try {
            if ($exception && $exception instanceof Throwable) {
                captureException($exception);
            }
        } catch (Exception $e) {
            if (DO_DEBUG) {
                throw $e;
            }
        }
```

throws this:

```
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Zend\Diactoros\normalizeUploadedFiles() must be of the type array, null given, called in /Users/mkovachev/sworkspace/payin7/payin7-web/vendor/zendframework/zend-diactoros/src/ServerRequestFactory.php on line 63 and defined in /Users/mkovachev/sworkspace/payin7/payin7-web/vendor/zendframework/zend-diactoros/src/functions/normalize_uploaded_files.php:25
Stack trace:
#0 /Users/mkovachev/sworkspace/payin7/payin7-web/vendor/zendframework/zend-diactoros/src/ServerRequestFactory.php(63): Zend\Diactoros\normalizeUploadedFiles(NULL)
#1 /Users/mkovachev/sworkspace/payin7/payin7-web/vendor/sentry/sentry/src/Integration/RequestIntegration.php(101): Zend\Diactoros\ServerRequestFactory::fromGlobals()
#2 /Users/mkovachev/sworkspace/payin7/payin7-web/vendor/sentry/sentry/src/Integration/RequestIntegration.php(74): Sentry\Integration\RequestIntegration-&gt;processEvent(Object(Sentry\Event), Object(Sentry\Options))
#3 /Users/mkovachev/sworkspace/payin7/payin7-web/vendor/sentry/sentry/src/S in <b>/Users/mkovachev/sworkspace/payin7/payin7-web/vendor/zendframework/zend-diactoros/src/functions/normalize_uploaded_files.php</b> on line <b>25</b><br />

```

**Comment by Jean85** [comment]
You're referring to a very old version of this package. We're currently on 2.x. Please upgrade.

Closing as wont fix.

**Comment by Jean85** [comment]
Sorry for closing so early. It seems that you're using `sentry/sentry` 2.x, is that correct?

**Comment by miraclebg** [comment]
My mistake! I was reading something else in composer.json.

Currently using: 2.1.3.
<img width="401" alt="Screenshot 2019-09-10 at 18 47 31" src="https://user-images.githubusercontent.com/126405/64629244-84d03380-d3fb-11e9-85d6-eab7b5cac192.png">

**Comment by Jean85** [comment]
The last two steps of the stacktrace are this one: https://github.com/getsentry/sentry-php/blob/2.1.3/src/Integration/RequestIntegration.php#L101

And afterwards this other one inside `zend/diactoros`: 
```php
        $files   = normalizeUploadedFiles($files ?: $_FILES);```
Since `$files` is an argument that we're not passing, `$_FILES` equals `null` and generates the erorr. This is really strange, since I would expect Diactoros to handle this pretty well; we previously had an issue there because we were invoking Diactoros under CLI, but we fixed that and we check the SAPI now.

@miraclebg where you in a CLI environment? Or did you otherwise alter the `$_FILES` global in any way? Can you confirm what version of Diactoros are you using?

**Comment by miraclebg** [comment]
Nope - i am not under CLI. Using php-fpm.

But you are correct $_FILES has been modified!

We are doing that to as we have other means of accessing it and thus to prevent others from using $_FILES directly - we actually do null-ify it.

I'll see if we can fix that to prevent issues with 3rdparty libs like yours :)

Thanks for the help!

**Comment by Jean85** [comment]
Setting it to `[]` instead of `null` (which seems the natural empty values) should do the trick!

Closing as not applicable. Feel free to reply further if needed.
